### ISSUE TITLE
pg_ext.so is still not found

### ISSUE THREAD

**Issue by tamvm** [stevenringo/lambda-ruby-pg-nokogiri#5]
I'm able to test the function locally with 
```
make && make install && make test
```

Then I built the deploy.zip and deploy but when runnning on Lambda it still raises an error
```
aws lambda invoke \
		--region ap-southeast-2 \
		--function-name RubyLambdaPostgreSQLNokogiri /dev/stdout
{"errorMessage":"libpq.so.5: cannot open shared object file: No such file or directory - /var/task/vendor/bundle/ruby/2.5.0/gems/pg-1.2.2/lib/pg_ext.so","errorType":"Init<LoadError>","stackTrace":["/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'","/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'","/var/task/vendor/bundle/ruby/2.5.0/gems/pg-1.2.2/lib/pg.rb:5:in `<top (required)>'","/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `require'","/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'","/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'","/var/task/handler.rb:1:in `<top (required)>'","/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'","/var/lang/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'"]}{
    "FunctionError": "Unhandled",
    "ExecutedVersion": "$LATEST",
    "StatusCode": 200
}
```

Anyone has any idea on that? 

Thank you

**Comment by nijeesh4all** [comment]
@tamvm  have you solved this issue?
